config/routes.rb
DaybookSpectrum::Application.routes.draw do

  resources :daybooks do
    resources :scientists
  end

  root :to => "daybooks#index"

end

app/models/daybook.rb
class Daybook < ActiveRecord::Base

  has_many :memberships
  has_many :scientists, :through => :memberships

  attr_accessible :name, :logo, :character_id
  has_attached_file :logo, :styles => { :thumb => "100x100>" }

  validates :name, :presence => true,
                   :length   => { :maximum => 50 }
  validates :logo, :presence => true

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :daybook
  belongs_to :scientist
end

app/models/scientist.rb
class Scientist < ActiveRecord::Base

  has_many :memberships
  has_many :daybooks, :through => :memberships

  attr_accessible :date, :description, :title

  validates :title, :presence => true,
                    :length => {:maximum => 50}
  validates :description, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/daybooks_controller.rb
class DaybooksController < ApplicationController

  def index
    @daybooks = Daybook.all
  end

  def show
    @daybook = Daybook.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def new
    @daybook = Daybook.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @daybook = Daybook.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def create
    @daybook = Daybook.new(params[:daybook])

    respond_to do |format|
      if @daybook.save
        format.html {redirect_to @daybook, notice: 'Daybook type was successfully created'}
      else
        format.html {render action: "new"}
      end
    end
  end

  def update
    @daybook = Daybook.find(params[:id])

    respond_to do |format|
      if @daybook.update_attributes(params[:daybook])
        format.html {redirect_to daybooks_path, notice: 'Daybook type was successfully updated'}
      else
        format.html {render action: "edit"}
      end
    end
  end

  def destroy
    @daybook.logo = nil
    @daybook = Daybook.find(params[:id])
    @daybook.destroy

    respond_to do |format|
      format.html {redirect_to daybooks_url}
    end
end

end

app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  def index
    @scientists = Scientist.all
  end

  def new
    @scientist = Scientist.new
  end

  def show
    @scientist = Scientist.find(params[:id])
  end

  def edit
    @scientist = Scientist.find(params[:id])
  end

  def create
    @scientist = Scientist.new(params[:scientist])

    respond_to do |format|
      if @scientist.save
        format.html {redirect_to @scientist, notice: 'Scientist\'s post was successfully created'}
      else
        format.html {render action: "new"}
      end
    end
  end

  def update
    @scientist = Scientist.find(params[:id])

    respond_to do |format|
      if @scientist.update_attributes(params[:scientist])
        format.html {redirect_to scientists_path, notice: 'Scientist\'s post was successfully updated'}
      else
        format.html {render action: "edit"}
      end
    end
  end

  def destroy
    @scientist = Scientist.find(params[:id])
    @scientist.destroy

    respond_to do |format|
      format.html {redirect_to scientists_path}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daybooks_helper.rb
module DaybooksHelper
end

app/helpers/scientists_helper.rb
module ScientistsHelper
end

app/views/daybooks/_form.html.slim
= form_for(@daybook) do |f|
  - if @daybook.errors.any?
    .errors_details
      - @daybook.errors.full_messages.each do |msg|
        div = msg


.form = form_for @daybook, :html => { :multipart => true } do |form|
  div = form.label :name
  .name_field = form.text_field :name
  div = form.label :character_id
  .name_field = form .text_field :character_id
  div = form.label :logo
  .logo_field = form.file_field :logo
  .submit_button = form.submit

app/views/daybooks/edit.html.slim
h1 Editing daybook type
= render 'form'

app/views/daybooks/index.html.slim
.site-name
  = image_tag "index.jpg"

- @daybooks.each do |daybook|
   div class="daybook_containers"
     div class="clearfix logo_container" = image_tag daybook.logo.url(:thumb)
     div class="clearfix" = link_to daybook.name, daybook_scientists_path(:daybook[params:id])

.add_new = link_to('Add daybook type', new_daybook_path)
.example = link_to('Британские ученые установили', scientists_path)

app/views/daybooks/new.html.slim
h1 Create daybook type
= render 'form'

app/views/daybooks/show.html.slim
.show
  div= image_tag @daybook.logo.url(:thumb)
  div= @daybook.name
  div class="links_container"
    p = link_to("edit", edit_daybook_path)
    p = link_to("back", daybooks_path)

app/views/layouts/application.html.slim
doctype html
html
  head
    title Daybook / Record book / Journal spectrum
    = stylesheet_link_tag "daybooks", "scientists"
    = javascript_include_tag "application"
    meta name="keywords" content="Daybook, spectrum, fun"
    meta name="description" content="Daybook spectrum / Record book spectrum / Journal spectrum"
  body
    .main = yield

app/views/scientists/_form.html.slim
= form_for(@scientist) do |f|
  - if @scientist.errors.any?
    .errors_details
      - @scientist.errors.full_messages.each do |msg|
        div = msg


.form = form_for @scientist, :html => { :multipart => true } do |form|
  div = form.label :title
  .name_field = form.text_field :title
  div = form.label :date
  .date_field = form.date_select :date
  div = form.label :description
  .desc_field = form.text_area :description
  .submit_button = form.submit

app/views/scientists/edit.html.slim
h1 Editing scientists note
= render 'form'

app/views/scientists/index.html.slim
.scientists
  h1 Warning! British scientist's last discoveries /
  - @scientists.last(10).each do |scientist|
    div class="scientist_container"
      div class="date" = scientist.date
      div class="title_container" = scientist.title
      div class="clearfix scientist_desc" = scientist.description
.add_new = link_to('Add scientific npost', new_scientist_path)

app/views/scientists/new.html.slim
h1 Create scientific post
= render 'form'

app/views/scientists/show.html.slim
.show
  div= @scientist.title
  div= @scientist.date
  div= @scientist.description
  div class="links_container"
    p = link_to("edit", edit_scientist_path)
    p = link_to("cancel", scientists_path)
    p = link_to 'delete', scientist_path(@scientist), method: :delete, confirm: 'Are you sure?'